{{- if .Values.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "layerhouse.fullname" . }}-server
  namespace: {{ include "layerhouse.namespace" . }}
spec:
  secretName: {{ .Values.server.tls.existingSecret }}
  issuerRef:
    name: {{ required "certManager.issuerRef.name is required when certManager.enabled=true" .Values.certManager.issuerRef.name }}
    kind: {{ .Values.certManager.issuerRef.kind }}
    group: {{ .Values.certManager.issuerRef.group }}
  dnsNames:
    - {{ include "layerhouse.fullname" . }}.{{ include "layerhouse.namespace" . }}.svc
    - {{ include "layerhouse.fullname" . }}.{{ include "layerhouse.namespace" . }}.svc.cluster.local
    {{- range .Values.server.tls.dnsNames }}
    - {{ . | quote }}
    {{- end }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "layerhouse.fullname" . }}-raft
  namespace: {{ include "layerhouse.namespace" . }}
spec:
  secretName: {{ .Values.raft.tls.existingSecret }}
  issuerRef:
    name: {{ required "certManager.issuerRef.name is required when certManager.enabled=true" .Values.certManager.issuerRef.name }}
    kind: {{ .Values.certManager.issuerRef.kind }}
    group: {{ .Values.certManager.issuerRef.group }}
  usages:
    - server auth
    - client auth
  dnsNames:
    - {{ include "layerhouse.fullname" . }}-headless
    - {{ include "layerhouse.fullname" . }}-headless.{{ include "layerhouse.namespace" . }}.svc
    - "*.{{ include "layerhouse.fullname" . }}-headless"
    - "*.{{ include "layerhouse.fullname" . }}-headless.{{ include "layerhouse.namespace" . }}.svc"
    - "*.{{ include "layerhouse.fullname" . }}-headless.{{ include "layerhouse.namespace" . }}.svc.cluster.local"
    {{- range $i := until (int .Values.replicaCount) }}
    - {{ include "layerhouse.fullname" $ }}-{{ $i }}.{{ include "layerhouse.fullname" $ }}-headless.{{ include "layerhouse.namespace" $ }}.svc
    - {{ include "layerhouse.fullname" $ }}-{{ $i }}.{{ include "layerhouse.fullname" $ }}-headless.{{ include "layerhouse.namespace" $ }}.svc.cluster.local
    {{- end }}
{{- end }}
