{{- if .Values.raft.kubernetes.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "layerhouse.fullname" . }}-statefulset-reader
  namespace: {{ include "layerhouse.namespace" . }}
  labels:
    {{- include "layerhouse.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - apps
    resources:
      - statefulsets
    resourceNames:
      - {{ default (include "layerhouse.fullname" .) .Values.raft.kubernetes.statefulSetName | quote }}
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "layerhouse.fullname" . }}-statefulset-reader
  namespace: {{ include "layerhouse.namespace" . }}
  labels:
    {{- include "layerhouse.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "layerhouse.serviceAccountName" . }}
    namespace: {{ include "layerhouse.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "layerhouse.fullname" . }}-statefulset-reader
{{- end }}
